export const DEFAULT_OFFER_COUNT = 60;

export const OFFER_CONSTRAINT = {
  MIN_TITLE: 10,
  MAX_TITLE: 100,
  MIN_DESCRIPTION: 20,
  MAX_DESCRIPTION: 1024,
  PHOTOS_LENGTH: 6,
  MIN_ROOMS: 1,
  MAX_ROOMS: 8,
  MIN_GUESTS: 1,
  MAX_GUESTS: 10,
  MIN_PRICE: 100,
  MAX_PRICE: 100000,
} as const;

export const PREMIUM_COUNT = 3;
