### Create Comment
POST http://localhost:10000/comments/
Content-Type: application/json

{
  "text": "Test comment. Neque egestas congue quisque egestas diam in. Quisque egestas diam in arcu cursus euismod quis. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Mattis pellentesque id nibh tortor. Morbi tempus iaculis urna id volutpat lacus. Non odio euismod lacinia at quis risus. In pellentesque massa placerat duis ultricies lacus. Dolor sed viverra ipsum nunc aliquet bibendum enim. Pretium quam vulputate dignissim suspendisse in est ante in nibh. Consectetur purus ut faucibus pulvinar elementum integer enim neque volutpat.",
  "rating": 3.6,
  "offerId": "6339141dd26fbbc45e4253bf",
  "userId": "6339141dd26fbbc45e4253c2"
}


### Show Comments By Offer
GET http://localhost:10000/comments/6339141dd26fbbc45e4253bf
