#Favorites
### Add to Favorites
POST {{baseUrl}}/favorites/63515618cab1187ebb68d3ae
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": 1
}


### Remove from Favorites
POST {{baseUrl}}/favorites/63515618cab1187ebb68d3ae
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "offerId": "63515618cab1187ebb68d3ae",
  "status": 0
}

### Get Favorites
GET {{baseUrl}}/favorites
Authorization: Bearer {{authToken}}

### Add to Favorites Invalid OfferId
POST {{baseUrl}}/favorites/63515618cab1187ebb68d3ad
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": 1
}


### Add to Favorites Invalid body
POST {{baseUrl}}/favorites/63515618cab1187ebb68d3ad
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": 2
}
