### Show Offers List
GET http://localhost:10000/offers?limit=5

### Create Offer
POST http://localhost:10000/offers
Content-Type: application/json

{
  "title": "New Offer 1",
  "description": "Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Feugiat vivamus at augue eget arcu dictum varius duis.",
  "city": {
    "name": "Hamburg",
    "location": {
      "latitude": 53.550341,
      "longitude": 10.000654
    }
  },
  "previewImage": "room-5.jpg",
  "photos": [
    "room-4-photo2.jpg",
    "room-5-photo1.jpg",
    "room-5-photo2.jpg"
  ],
  "isPremium": false,
  "type": "Hotel",
  "rooms": 8,
  "guests": 8,
  "price": 750,
  "features": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "userId": "6339141dd26fbbc45e4253bd",
  "location": {
    "latitude": 48.571118,
    "longitude": 4.729841
  }
}

### Show One Offer
GET http://localhost:10000/offers/6339141dd26fbbc45e4253bf

### Update Offer
PATCH http://localhost:10000/offers/633ea92fb68d621eb85fd4d4
Content-Type: application/json

{
  "title": "New Test Offer"
}

### Remove Offer
DELETE http://localhost:10000/offers/634036514abd8ec4b8e44e62

### Show Premium Offers
GET http://localhost:10000/offers/Paris/premium

### Invalid ID
GET http://localhost:10000/offers/6339141

### Invalid Offer Data
POST http://localhost:10000/offers
Content-Type: application/json

{
  "title": "New",
  "description": "Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Feugiat vivamus at augue eget arcu dictum varius duis.",
  "city": {
    "name": "Hamburg",
    "location": {
      "latitude": 53.550341,
      "longitude": 10.000654
    }
  },
  "previewImage": "room-5.jpg",
  "photos": [
    "room-4-photo2.jpg",
    "room-5-photo1.jpg",
    "room-5-photo2.jpg"
  ],
  "isPremium": false,
  "type": "Hotel",
  "rooms": 8,
  "guests": 8,
  "price": 750,
  "features": [
    "Breakfast",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "userId": "6339141dd26fbbc45e4253bd",
  "location": {
    "latitude": 48.571118,
    "longitude": 4729841
  }
}

### Document not exist Show One Offer
GET http://localhost:10000/offers/6339141dd26fbbc45e4253b3
