### Create User
POST http://localhost:10000/users/register
Content-Type: application/json

{
  "email": "user10@gmail.com",
  "avatar": "user-avatar.jpg",
  "userName": "user1",
  "password": "secret123",
  "userType": "Default"
}

### Login User
POST http://localhost:10000/users/login
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "secret123"
}

### Invalid Create User
POST http://localhost:10000/users/register
Content-Type: application/json

{
  "email": "user1gmail.com",
  "avatar": "user-avatar.gif",
  "userName": "user1",
  "password": "secret123",
  "userType": ""
}

### Invalid Login User
POST http://localhost:10000/users/login
Content-Type: application/json

{
  "email": "user1gmail.com",
  "password": "sec"
}
