#Favorites
### Add to Favorites
POST {{baseUrl}}/favorites/634c13e3f89a4bf8048054c9/1
Authorization: Bearer {{authToken}}

### Remove from Favorites
POST {{baseUrl}}/favorites/634c13e3f89a4bf8048054c9/0
Authorization: Bearer {{authToken}}

### Get Favorites
GET {{baseUrl}}/favorites
Authorization: Bearer {{authToken}}

### Add to Favorites Invalid OfferId
POST {{baseUrl}}/favorites/63515618cab1187ebb68d3ad/1
Authorization: Bearer {{authToken}}
Content-Type: application/json
